<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <OutputType>WinExe</OutputType>
    <RootNamespace>CIDE</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <ApplicationTitle>CIDE</ApplicationTitle>
    <ApplicationId>com.core.cide</ApplicationId>
    <ApplicationIcon>Assets\cide_logo.ico</ApplicationIcon>

    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <!-- 1. Ядро Avalonia -->
    <PackageReference Include="Avalonia" Version="11.3.14" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.14" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.14" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.14" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.14" />

    <!-- 2. Иконки -->
    <PackageReference Include="Avalonia.Svg.Skia" Version="11.3.0" />

    <!-- 3. Редактор кода -->
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.1.0" />
    <PackageReference Include="AvaloniaEdit.TextMate" Version="11.1.0" />

    <!-- 4. Наш капризный Терминал -->
    <PackageReference Include="Iciclecreek.Avalonia.Terminal" Version="1.0.12" />

    <!-- 5. Остальные библиотеки -->
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.8" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.8" />

    <!-- СТРОКА С TextMateSharp.Grammars УДАЛЕНА ПОЛНОСТЬЮ! -->
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\**\*" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**\*" />
  </ItemGroup>
  
</Project>