<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <OutputType>WinExe</OutputType>
    <RootNamespace>CIDE</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <ApplicationTitle>CIDE</ApplicationTitle>
    <ApplicationId>com.core.cide</ApplicationId>

    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <!-- Avalonia UI -->
    <PackageReference Include="Avalonia" Version="12.0.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.3" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.16" />
    
    <!-- AvaloniaEdit -->
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageReference Include="AvaloniaEdit.TextMate" Version="12.0.0" />

    <!-- MVVM and DI -->
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    
    <!-- Utilities -->
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
    <PackageReference Include="TextMateSharp.Grammars" Version="2.0.3" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\cide_logo.png" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**\*" />
  </ItemGroup>

</Project>